### ISSUE TITLE
Track Component

### ISSUE THREAD

**Issue by jordanwillis** [saahil0826/jammming#5]
Watch out for cases where you try to access a prop without using the props object.  In this example, `isRemoval` is undefined because it exists within your props.

https://github.com/saahil0826/jammming/blob/master/src/Components/Track/Track.js#L16

Instead it would look something like this.

``` javascript
if (this.props.isRemoval) {

}
```

Also, be careful about the order of your add/remove logic.  You currently have it backwards (e.g. if `isRemoval` is true then you need to remove the track...however you are currently trying to add the track).

https://github.com/saahil0826/jammming/blob/fcfdcc42b76a51b9312b3456521e0c8ce1029499/src/Components/Track/Track.js#L16-L21

So just switch those and you will be good.

Lastly, don't forget to use the Track component to display the actual track information (e.g. track name, artist, and album).  I see that you have some placeholders there in the form of HTML comments, but now that your app is complete you should take these values from your props.

So instead or this...

https://github.com/saahil0826/jammming/blob/fcfdcc42b76a51b9312b3456521e0c8ce1029499/src/Components/Track/Track.js#L34-L40

It would be something like this...

``` javascript
<div className="Track">
  <div className="Track-information">
    <h3>{this.props.track.name}</h3>
    <p>{this.props.track.artist} | {this.props.track.album}</p>
  </div>
  {this.renderAction()}
</div>
```

Which means you need to pass in those props from your TrackList component's render function.  Your current implementation is displaying the track's info directly from the TrackList instead of letting the Track handle it via props.

https://github.com/saahil0826/jammming/blob/fcfdcc42b76a51b9312b3456521e0c8ce1029499/src/Components/Tracklist/TrackList.js#L11-L21

You will want to drop those `<p>` elements and just pass the data to your Track component.

``` javascript
this.props.tracks.map(track => {
  return <Track track={track}
                key={track.id}
                onAdd={this.props.onAdd}
                isRemoval={this.props.isRemoval}
                onRemove={this.props.onRemove} />
})
```

**Comment by saahil0826** [comment]
ok, i made this change and it is mandatory right, to but all the elements inside one parent element while writing react code. so it the below code fine?

`class TrackList extends React.Component {
  render() {
    return (
      <div className="TrackList">
      {
        this.props.tracks.map(track => {
          return (
            <div>
              <Track track = {track}
              key={track.id}
              onAdd = {this.props.onAdd}
              onRemove = {this.props.onRemove}
              isRemoval = {this.props.isRemoval} />
            </div>
          )
        })
      }
      </div>
    );
  }
}
`

**Comment by jordanwillis** [comment]
I wasn't really able to analyze your new code in your response due to formatting issues, but it looks correct to me.  Here is my solution that you can use to compare.

``` javascript
render() {
  return (
    <div className="TrackList">
      {
        this.props.tracks.map(track => {
          return <Track track={track}
                        key={track.id}
                        onAdd={this.props.onAdd}
                        isRemoval={this.props.isRemoval}
                        onRemove={this.props.onRemove} />
        })
      }
    </div>
  );
}
```
